import { defineSchema } from "@datafn/core";

const id = { name: "id", type: "string", required: true, readonly: true } as const;
const createdAt = {
  name: "createdAt",
  type: "date",
  required: true,
  readonly: true,
} as const;
const updatedAt = {
  name: "updatedAt",
  type: "date",
  required: true,
  readonly: true,
} as const;

function readOnly(fields: readonly string[]) {
  return { read: { fields: [...fields] }, write: { fields: [] } };
}

export const skillplaneDatafnSchema = defineSchema({
  version: 1,
  namespaced: true,
  resources: [
    {
      name: "workspaces",
      version: 1,
      fields: [
        id,
        { name: "kind", type: "string", required: true, readonly: true },
        { name: "slug", type: "string", required: true, readonly: true },
        { name: "name", type: "string", required: true, readonly: true },
        { name: "metadata", type: "json", required: true, readonly: true },
        createdAt,
        updatedAt,
      ],
      indices: { base: ["slug"], search: ["name"] },
      permissions: readOnly([
        "id",
        "kind",
        "slug",
        "name",
        "metadata",
        "createdAt",
        "updatedAt",
      ]),
    },
    {
      name: "workspaceMemberships",
      version: 1,
      fields: [
        id,
        { name: "userId", type: "string", required: true, readonly: true },
        { name: "role", type: "string", required: true, readonly: true },
        createdAt,
        updatedAt,
      ],
      indices: { base: ["userId", "role"] },
      permissions: readOnly(["id", "userId", "role", "createdAt", "updatedAt"]),
    },
    {
      name: "skills",
      version: 1,
      fields: [
        id,
        { name: "slug", type: "string", required: true, readonly: true },
        { name: "name", type: "string", required: true, readonly: true },
        { name: "description", type: "string", required: true, readonly: true },
        { name: "tags", type: "array", required: true, readonly: true },
        { name: "visibility", type: "string", required: true, readonly: true },
        { name: "amendmentPolicy", type: "json", required: true, readonly: true },
        {
          name: "currentPublishedVersionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
        updatedAt,
        {
          name: "archivedAt",
          type: "date",
          required: false,
          nullable: true,
          readonly: true,
        },
      ],
      indices: { base: ["slug", "updatedAt"], search: ["name", "description"] },
      permissions: readOnly([
        "id",
        "slug",
        "name",
        "description",
        "tags",
        "visibility",
        "amendmentPolicy",
        "currentPublishedVersionId",
        "createdAt",
        "updatedAt",
        "archivedAt",
      ]),
    },
    {
      name: "skillVersions",
      version: 1,
      fields: [
        id,
        { name: "skillId", type: "string", required: true, readonly: true },
        { name: "revision", type: "number", required: true, readonly: true },
        {
          name: "semanticVersion",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "status", type: "string", required: true, readonly: true },
        {
          name: "baseVersionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "proposedBump",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "source", type: "string", required: true, readonly: true },
        { name: "contentDigest", type: "string", required: true, readonly: true },
        { name: "bundleByteSize", type: "number", required: true, readonly: true },
        { name: "manifest", type: "json", required: true, readonly: true },
        { name: "learningMetadata", type: "json", required: true, readonly: true },
        {
          name: "amendmentOperations",
          type: "json",
          required: true,
          readonly: true,
        },
        { name: "callerDeclaration", type: "json", required: true, readonly: true },
        { name: "policyDecision", type: "json", required: true, readonly: true },
        { name: "changeSummary", type: "string", required: true, readonly: true },
        {
          name: "createdByActorType",
          type: "string",
          required: true,
          readonly: true,
        },
        { name: "createdByActorId", type: "string", required: true, readonly: true },
        {
          name: "createdByAgent",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdByModel",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdForUserId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "publishedAt",
          type: "date",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
      ],
      indices: { base: ["skillId", "revision", "status"] },
      permissions: readOnly([
        "id",
        "skillId",
        "revision",
        "semanticVersion",
        "status",
        "baseVersionId",
        "proposedBump",
        "source",
        "contentDigest",
        "bundleByteSize",
        "manifest",
        "learningMetadata",
        "amendmentOperations",
        "callerDeclaration",
        "policyDecision",
        "changeSummary",
        "createdByActorType",
        "createdByActorId",
        "createdByAgent",
        "createdByModel",
        "createdForUserId",
        "publishedAt",
        "createdAt",
      ]),
    },
    {
      name: "skillContexts",
      version: 1,
      fields: [
        id,
        { name: "skillId", type: "string", required: true, readonly: true },
        { name: "slug", type: "string", required: true, readonly: true },
        { name: "name", type: "string", required: true, readonly: true },
        { name: "contextType", type: "string", required: true, readonly: true },
        {
          name: "externalReference",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "description", type: "string", required: true, readonly: true },
        { name: "metadata", type: "json", required: true, readonly: true },
        {
          name: "currentKnowledgeRevisionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
        updatedAt,
        {
          name: "archivedAt",
          type: "date",
          required: false,
          nullable: true,
          readonly: true,
        },
      ],
      indices: { base: ["skillId", "slug"], search: ["name", "description"] },
      permissions: readOnly([
        "id",
        "skillId",
        "slug",
        "name",
        "contextType",
        "externalReference",
        "description",
        "metadata",
        "currentKnowledgeRevisionId",
        "createdAt",
        "updatedAt",
        "archivedAt",
      ]),
    },
    {
      name: "contextKnowledgeRevisions",
      version: 1,
      fields: [
        id,
        { name: "contextId", type: "string", required: true, readonly: true },
        { name: "revision", type: "number", required: true, readonly: true },
        {
          name: "baseRevisionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "knowledge", type: "string", required: true, readonly: true },
        { name: "bodyDigest", type: "string", required: true, readonly: true },
        { name: "learningMetadata", type: "json", required: true, readonly: true },
        {
          name: "createdByActorType",
          type: "string",
          required: true,
          readonly: true,
        },
        { name: "createdByActorId", type: "string", required: true, readonly: true },
        {
          name: "createdByAgent",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdByModel",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdForUserId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
      ],
      indices: { base: ["contextId", "revision"], search: ["knowledge"] },
      permissions: readOnly([
        "id",
        "contextId",
        "revision",
        "baseRevisionId",
        "knowledge",
        "bodyDigest",
        "learningMetadata",
        "createdByActorType",
        "createdByActorId",
        "createdByAgent",
        "createdByModel",
        "createdForUserId",
        "createdAt",
      ]),
    },
    {
      name: "contextNotes",
      version: 1,
      fields: [
        id,
        { name: "contextId", type: "string", required: true, readonly: true },
        { name: "noteKey", type: "string", required: true, readonly: true },
        { name: "title", type: "string", required: true, readonly: true },
        {
          name: "currentRevisionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
        updatedAt,
        {
          name: "archivedAt",
          type: "date",
          required: false,
          nullable: true,
          readonly: true,
        },
      ],
      indices: { base: ["contextId", "noteKey"], search: ["title"] },
      permissions: readOnly([
        "id",
        "contextId",
        "noteKey",
        "title",
        "currentRevisionId",
        "createdAt",
        "updatedAt",
        "archivedAt",
      ]),
    },
    {
      name: "contextNoteRevisions",
      version: 1,
      fields: [
        id,
        { name: "noteId", type: "string", required: true, readonly: true },
        { name: "revision", type: "number", required: true, readonly: true },
        {
          name: "baseRevisionId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "title", type: "string", required: true, readonly: true },
        { name: "body", type: "string", required: true, readonly: true },
        { name: "bodyDigest", type: "string", required: true, readonly: true },
        { name: "learningMetadata", type: "json", required: true, readonly: true },
        {
          name: "createdByActorType",
          type: "string",
          required: true,
          readonly: true,
        },
        { name: "createdByActorId", type: "string", required: true, readonly: true },
        {
          name: "createdByAgent",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdByModel",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "createdForUserId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
      ],
      indices: { base: ["noteId", "revision"], search: ["body"] },
      permissions: readOnly([
        "id",
        "noteId",
        "revision",
        "baseRevisionId",
        "title",
        "body",
        "bodyDigest",
        "learningMetadata",
        "createdByActorType",
        "createdByActorId",
        "createdByAgent",
        "createdByModel",
        "createdForUserId",
        "createdAt",
      ]),
    },
    {
      name: "amendmentReviews",
      version: 1,
      fields: [
        id,
        { name: "skillId", type: "string", required: true, readonly: true },
        {
          name: "proposedVersionId",
          type: "string",
          required: true,
          readonly: true,
        },
        { name: "status", type: "string", required: true, readonly: true },
        {
          name: "decisionReason",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "requestedByActorType",
          type: "string",
          required: true,
          readonly: true,
        },
        {
          name: "requestedByActorId",
          type: "string",
          required: true,
          readonly: true,
        },
        {
          name: "requestedByAgent",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "requestedByModel",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "requestedForUserId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "reviewedByUserId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "reviewedByActorType",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        {
          name: "reviewedByActorId",
          type: "string",
          required: false,
          nullable: true,
          readonly: true,
        },
        { name: "policyDecision", type: "json", required: true, readonly: true },
        {
          name: "reviewedAt",
          type: "date",
          required: false,
          nullable: true,
          readonly: true,
        },
        createdAt,
        updatedAt,
      ],
      indices: { base: ["skillId", "status"] },
      permissions: readOnly([
        "id",
        "skillId",
        "proposedVersionId",
        "status",
        "decisionReason",
        "requestedByActorType",
        "requestedByActorId",
        "requestedByAgent",
        "requestedByModel",
        "requestedForUserId",
        "reviewedByUserId",
        "reviewedByActorType",
        "reviewedByActorId",
        "policyDecision",
        "reviewedAt",
        "createdAt",
        "updatedAt",
      ]),
    },
    {
      name: "analyticsDaily",
      version: 1,
      fields: [
        { name: "day", type: "string", required: true, readonly: true },
        { name: "skillId", type: "string", required: true, readonly: true },
        { name: "contextId", type: "string", required: true, readonly: true },
        { name: "agent", type: "string", required: true, readonly: true },
        { name: "model", type: "string", required: true, readonly: true },
        { name: "retrievalCount", type: "number", required: true, readonly: true },
        { name: "amendmentCount", type: "number", required: true, readonly: true },
        { name: "contextWriteCount", type: "number", required: true, readonly: true },
        updatedAt,
      ],
      indices: { base: ["day", "skillId", "contextId"] },
      permissions: readOnly([
        "day",
        "skillId",
        "contextId",
        "agent",
        "model",
        "retrievalCount",
        "amendmentCount",
        "contextWriteCount",
        "updatedAt",
      ]),
    },
  ],
  relations: [
    {
      from: "skills",
      to: "skillVersions",
      type: "many-one",
      relation: "currentVersion",
      fkField: "currentPublishedVersionId",
    },
  ],
});

export const DATAFN_RESOURCE_NAMES = skillplaneDatafnSchema.resources.map(
  (resource) => resource.name,
);

export const DATAFN_SECRET_TABLES = [
  "authfnUsers",
  "authfnSessions",
  "workspaceInvitations",
  "servicePrincipals",
  "skillVersionFiles",
  "auditEvents",
  "idempotencyRecords",
  "apiRateLimits",
  "oauthClients",
  "oauthClientRedirectUris",
  "oauthConsents",
  "oauthAuthorizationRequests",
  "oauthAuthorizationCodes",
  "oauthAccessTokens",
  "oauthRefreshTokens",
] as const;
